# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'RandomFood' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'WCDB.swift'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Bugly'
end
